apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-for-app
data:
  # property-like keys; each key maps to a simple value
  VAR_1: "tributes to the sun"
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    