apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    type: hostPath
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker
    